# Model Routing Configuration
# This file controls which AI models are used for different types of requests
# Update models here and they will be automatically applied to the system

model_routing:
  description: "Production Model Routing Configuration - Sprint 3"
  version: "3.0.0"
  models:
    image_generation:
      NEW_IMAGE:
        model: "black-forest-labs/flux-1.1-pro"
        generator: "replicate"
      NEW_IMAGE_REF:
        model: "runway_gen4_image" 
        generator: "runway"
      EDIT_IMAGE:
        model: "black-forest-labs/flux-kontext-max"
        generator: "replicate"
      EDIT_IMAGE_REF:
        model: "runway_gen4_image"
        generator: "runway"
      EDIT_IMAGE_ADD_NEW:
        model: "runway_gen4_image"
        generator: "runway"
    
    video_generation:
      NEW_VIDEO:
        model: "minimax/hailuo-02"
        generator: "replicate"
        fallback_model: "google/veo-3-fast"
      NEW_VIDEO_WITH_AUDIO:
        model: "google/veo-3-fast"
        generator: "replicate"
        # No fallback - VEO-3-Fast is the only option for audio
      IMAGE_TO_VIDEO:
        model: "gen3a_turbo"
        generator: "runway"
        # No fallback - Runway is primary for image-to-video (bypass Hailuo-02 safety restrictions)
      IMAGE_TO_VIDEO_WITH_AUDIO:
        model: "google/veo-3-fast"
        generator: "replicate"
        # No fallback - VEO-3-Fast is the only option for audio
      EDIT_IMAGE_REF_TO_VIDEO:
        model: "gen3a_turbo"
        generator: "runway"
        # No fallback - Runway is primary for image-to-video
  


# Model selection weights (for routing decisions)
model_weights:
  quality_priority:
    "gen4_turbo": 1.0
    "veo-3.0-generate-preview": 0.95
    "gen3a_turbo": 0.9
    "minimax/hailuo-02": 0.88
    "veo-2.0-generate-001": 0.85
    "google/veo-3-fast": 0.8
    "flux-1.1-pro": 1.0
    "flux-dev": 0.9
  
  cost_priority:
    "minimax/hailuo-02": 1.0
    "google/veo-3-fast": 0.95
    "flux-dev": 1.0
    "flux-1.1-pro": 0.9
    "veo-2.0-generate-001": 0.8
    "veo-3.0-generate-preview": 0.7
    "gen3a_turbo": 0.6
    "gen4_turbo": 0.5
  
  speed_priority:
    "minimax/hailuo-02": 1.0
    "google/veo-3-fast": 0.95
    "flux-dev": 1.0
    "flux-1.1-pro": 0.9
    "gen3a_turbo": 0.8
    "gen4_turbo": 0.75
    "veo-2.0-generate-001": 0.7
    "veo-3.0-generate-preview": 0.6

  # Routing Rules Configuration
  routing_rules:
    
    # Audio detection rules
    audio_detection:
      enabled: true
      audio_keywords: 
        - "singing"
        - "song" 
        - "music"
        - "audio"
        - "sound"
        - "voice"
        - "speak"
        - "talk"
        - "lyrics"
        - "melody"
        - "vocal"
        - "narration"
        - "dialogue"
        - "conversation"
        - "interview"
        - "interviewing"
        - "reporter"
        - "news report"
        - "press conference"
        - "Q&A"
        - "asking questions"
        - "discussion"
        - "debate"
        - "meeting"
        - "presentation"
        - "lecture"
        - "speech"
        - "announcement"
        - "characters talking"
        - "phone call"
        - "video call"
        - "broadcasting"
        - "podcasting"
        - "storytelling"
    
    # Multi-reference handling
    multi_reference_routing:
      enabled: true
      threshold: 2
      target_model: "runway_gen4_image"
      applies_to: ["NEW_IMAGE_REF", "EDIT_IMAGE_REF"]
      
    # Fallback routing
    fallback_routing:
      enabled: true
      rules:
        - from: "runway_gen4_image"
          to: "black-forest-labs/flux-1.1-pro"
          condition: "api_error"
        - from: "veo-2.0-generate-001"
          to: "minimax/video-01"
          condition: "api_error"
          
    # Cost-based routing
    cost_based_routing:
      enabled: true
      cost_thresholds:
        low: 0.10
        medium: 0.25
        high: 0.50
      preferences:
        prefer_lower_cost: true
        
    # Quality-based routing
    quality_routing:
      enabled: true
      quality_preferences:
        image_quality: "high"
        video_quality: "high"
        audio_quality: "high"
        
    # Performance-based routing
    performance_routing:
      enabled: true
      max_generation_time: 300
      timeout_fallback: true